# Generated by Django 3.1 on 2020-08-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xmag_Blog', '0004_auto_20200808_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
