# Generated by Django 3.1 on 2020-08-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xmag_Blog', '0008_auto_20200808_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[(1, 'JavaScript'), (2, 'jQuery'), (3, 'Web Design'), (4, 'CSS')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
